### ISSUE TITLE
[PLE1300] ruff throws PLE1300 error in variable width string formatting

### ISSUE THREAD

**Issue by SigureMo** [astral-sh/ruff#6522] opened 2023-08-12 10:30 UTC
The minimum reproduction code is as follows:

```python
# ruff-PLE1300-repro.py
"{:^{}}".format("string", 10)
```

The second curly brackets is used to indicate the width of the formatting.

```bash
$ ruff --version     
ruff 0.0.284

$ ruff ruff-PLE1300-repro.py --select=PLE1300
ruff-PLE1300-repro.py:1:1: PLE1300 Unsupported format character '}'
Found 1 error.
```

**Comment by charliermarsh** [comment] 2023-08-12 13:23
Thanks — duplicate of https://github.com/astral-sh/ruff/issues/6442.

**Closed by charliermarsh** 2023-08-12 13:23 UTC
