### ISSUE TITLE
pep8 rules and autopep8

### ISSUE THREAD

**Issue by IamRezaMousavi** [astral-sh/ruff#5564] opened 2023-07-06 15:25 UTC
See standard style guide for Python code [pep8](https://peps.python.org/pep-0008/) and [autopep8](https://pypi.org/project/autopep8/)

![Screenshot from 2023-07-06 18-51-04](https://github.com/astral-sh/ruff/assets/83984878/fe45e0a8-28b2-4a1f-a286-4371f24b7056)

**Comment by zanieb** [comment] 2023-07-06 15:27
Hi @IamRezaMousavi thanks for opening an issue. Could you please include more details about what you expect here?

**Comment by IamRezaMousavi** [comment] 2023-07-06 15:41
> Hi @IamRezaMousavi thanks for opening an issue. Could you please include more details about what you expect here?

pep8 rules must implement in ruff.
Some rules like:
* `String Quotes`
* `Whitespace in Expressions and Statements`
* And other rules

We can implement `--fix` for this rules like `autopep8`

**Comment by charliermarsh** [comment] 2023-07-06 15:42
I _think_ this can be considered a duplicate of https://github.com/astral-sh/ruff/issues/2402, which covers the pycodestyle rules, which in turn cover PEP 8.

**Closed by charliermarsh** 2023-07-06 15:42 UTC
