### ISSUE TITLE
Unwelcome Error: memory allocation failed

### ISSUE THREAD

**Issue by rumbarum** [astral-sh/ruff#9729] opened 2024-01-31 06:50 UTC
ruff 0.1.13 installed by brew
MBP M1 mac 14.1.2

I am using ruff on Pycharm Filewatcher to trigger when file saved, it had been worked for 2 weeks. Now it return this error message
```
/opt/homebrew/bin/ruff format --config ~/ruff.toml /pycharm/file/path
memory allocation of 8751445353061442862 bytes failed

Process finished with exit code 134 (interrupted by signal 6:SIGABRT)
```

This is my ruff config from ~/ruff.toml,

```
line-length = 100
exclude = ["*/__init__.py"]

[lint]
# F=pyflakes
# I=Isort
select = ["F", "I"]

#F541 f-string without any placeholders
#F841 local variable '...' is assigned to but never used
#F403 from {name} import * used; unable to detect undefined names
#F401 '...' imported but unused --> Makefile (make ruff)에서만, 사용 강제합니다.
ignore = ["F541", "F841", "F401", "F403"]
fixable = ["ALL"]

[isort]
relative-imports-order = "closest-to-furthest"

[format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"
```

**Comment by MichaReiser** [comment] 2024-01-31 07:31
We're sorry you're encountering this issue and the unwelcome error message. 

We've been trying to identify the root cause of it in https://github.com/astral-sh/ruff/issues/8147 but have since been unable to reproduce it. It would be extremely helpful to us if you could share your cache state, commit version, and link to your project if it is an open source project so that we can reproduce locally and fix the issue. 

I'll close this issue to track the work in https://github.com/astral-sh/ruff/issues/8147

**Closed by MichaReiser** 2024-01-31 07:31 UTC
