### ISSUE TITLE
Support for legacy code base - baseline

### ISSUE THREAD

**Issue by Pixel-Minions** [astral-sh/ruff#5391] opened 2023-06-27 14:16 UTC
Hi, 

Thank for such a cool tool.
I am currently working with a huge monolithic old code base. I am planning to use a linter like ruff with only new code, so I don't have old errors appearing in thr console. It is possible to create a baseline so only the new code gets lint?

**Comment by charliermarsh** [comment] 2023-06-27 15:27
Thank you :)

I think this is a duplicate of #1149. Unfortunately, it's not something we support right now -- maybe some day. The only alternatives you would have are (1) running `ruff check --add-noqa /path/to/src` to automatically add suppression comments to existing violations, or (2) only enabling a subset of checks for now, and fixing all violations for that subset.

**Comment by charliermarsh** [comment] 2023-06-27 15:28
(I do empathize with this need and acknowledge that we don't have a great solution for it right now.)

**Closed by charliermarsh** 2023-06-27 15:27 UTC
