### ISSUE TITLE
Failed to install: certifi-2024.8.30-py3-none-any.whl

### ISSUE THREAD

**Issue by Pdsantos73** [astral-sh/ruff#13612] opened 2024-10-03 17:23 UTC
Trying to install fastapi "uv add fastapi[standard]" is showing the following error:

error: Failed to install: certifi-2024.8.30-py3-none-any.whl (certifi==2024.8.30)
  Caused by: failed to hardlink file from C:\Users\paulodo\AppData\Local\uv\cache\archive-v0\ez_A-yAgnUYbpxYugeHkX\certifi\py.typed to C:\Users\paulodo\OneDrive - Genesys Telecommunications Laboratories, Inc\DeveloperProject\Python\GenesysClould\middleware_a\.venv\Lib\site-packages\certifi\py.typed
  Caused by: The cloud operation cannot be performed on a file with incompatible hardlinks. (os error 396)

**Comment by dhruvmanila** [comment] 2024-10-04 04:28
Duplicate of https://github.com/astral-sh/uv/issues/7906 where the issue belongs

**Closed by dhruvmanila** 2024-10-04 04:28 UTC
