### ISSUE TITLE
Cache behaves differently with and without cache (`INP001`)

### ISSUE THREAD

**Issue by bersbersbers** [astral-sh/ruff#9543] opened 2024-01-16 06:49 UTC
`INP001` is issued after creating `__init__.py`, due to caching and potentially due to `N999`:

```
$ tree /f
C:.
├───example
│       generate-example.py
│
└───project
        main.py
        __init__.py

$ ruff --no-cache --isolated --select INP,N .
example\generate-example.py:1:1: INP001 File `example\generate-example.py` is part of an implicit namespace package. Add an `__init__.py`.
Found 1 error.

$ ruff --isolated --select INP,N .
example\generate-example.py:1:1: INP001 File `example\generate-example.py` is part of an implicit namespace package. Add an `__init__.py`.
Found 1 error.

$ echo. > example\__init__.py

$ tree /f
C:.
├───example
│       generate-example.py
│       __init__.py
│
└───project
        main.py
        __init__.py

$ ruff --no-cache --isolated --select INP,N .
example\generate-example.py:1:1: N999 Invalid module name: 'generate-example'
Found 1 error.

(So far, so good)

$ ruff --isolated --select INP,N .
example\generate-example.py:1:1: INP001 File `example\generate-example.py` is part of an implicit namespace package. Add an `__init__.py`.
Found 1 error.

$ ruff --isolated --select INP,N . --fix
example\generate-example.py:1:1: N999 Invalid module name: 'generate-example'
Found 1 error.

$ ruff --isolated --select INP,N .
example\generate-example.py:1:1: INP001 File `example\generate-example.py` is part of an implicit namespace package. Add an `__init__.py`.
Found 1 error.

$ ruff --version
ruff 0.1.13
```

**Comment by charliermarsh** [comment] 2024-01-16 19:36
I think this is a duplicate of https://github.com/astral-sh/ruff/issues/5449. (I think `--fix` is helping because we avoid reading the cache when applying fixes.)

**Closed by charliermarsh** 2024-01-16 19:36 UTC

**Comment by charliermarsh** [comment] 2024-01-16 22:49
All good, no worries!

**Comment by minakhanwattoo55-ai** [comment] 2026-04-27 13:30
$ tree /f
C:.
├───example
│       generate-example.py
│
└───project
        main.py
        __init__.py

$ ruff --no-cache --isolated --select INP,N .
example\generate-example.py:1:1: INP001 File `example\generate-example.py` is part of an implicit namespace package. Add an `__init__.py`.
Found 1 error.

$ ruff --isolated --select INP,N .
example\generate-example.py:1:1: INP001 File `example\generate-example.py` is part of an implicit namespace package. Add an `__init__.py`.
Found 1 error.

$ echo. > example\__init__.py

$ tree /f
C:.
├───example
│       generate-example.py
│       __init__.py
│
└───project
        main.py
        __init__.py

$ ruff --no-cache --isolated --select INP,N .
example\generate-example.py:1:1: N999 Invalid module name: 'generate-example'
Found 1 error.

(So far, so good)

$ ruff --isolated --select INP,N .
example\generate-example.py:1:1: INP001 File `example\generate-example.py` is part of an implicit namespace package. Add an `__init__.py`.
Found 1 error.

$ ruff --isolated --select INP,N . --fix
example\generate-example.py:1:1: N999 Invalid module name: 'generate-example'
Found 1 error.

$ ruff --isolated --select INP,N .
example\generate-example.py:1:1: INP001 File `example\generate-example.py` is part of an implicit namespace package. Add an `__init__.py`.
Found 1 error.

$ ruff --version
ruff 0.1.13
