### ISSUE TITLE
[Panic] in pre-commit with v0.0.273

### ISSUE THREAD

**Issue by stumpylog** [astral-sh/ruff#5225] opened 2023-06-20 22:06 UTC
After updating my pre-commit hook from 0.0.272 to 0.0.273, running `ruff` via pre-commit fails with a panic.  Running ruff manually at the same version works without issue.  There's no pyproject, and my .ruff.toml was unchanged. Running just the ruff hook also works find. I've removed `~/.cache/pre-commit` to get a fresh copy, which still fails.

After setting RUST_BACKTRACE=1, the log is as below:

```log
ruff.....................................................................Failed
- hook id: ruff
- exit code: 101

error: `ruff` crashed. This indicates a bug in `ruff`. If you could open an issue at:

https://github.com/astral-sh/ruff/issues/new?title=%5BPanic%5D

quoting the executed command, along with the relevant file contents and `pyproject.toml` settings, we'd be very appreciative!

thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', crates\ruff_cli\src\commands\run.rs:
error: `ruff` crashed. This indicates a bug in `ruff`. If you could open an issue at:

https://github.com/astral-sh/ruff/issues/new?title=%5BPanic%5D

quoting the executed command, along with the relevant file contents and `pyproject.toml` settings, we'd be very appreciative!

thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', crates\ruff_cli\src\commands\run.rs:112:65
112:65
stack backtrace:

error: `ruff` crashed. This indicates a bug in `ruff`. If you could open an issue at:

https://github.com/astral-sh/ruff/issues/new?title=%5BPanic%5D

quoting the executed command, along with the relevant file contents and `pyproject.toml` settings, we'd be very appreciative!

thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', crates\ruff_cli\src\commands\run.rs:112:65

error: `ruff` crashed. This indicates a bug in `ruff`. If you could open an issue at:

https://github.com/astral-sh/ruff/issues/new?title=%5BPanic%5D

quoting the executed command, along with the relevant file contents and `pyproject.toml` settings, we'd be very appreciative!

thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', crates\ruff_cli\src\commands\run.rs:112:65

error: `ruff` crashed. This indicates a bug in `ruff`. If you could open an issue at:

https://github.com/astral-sh/ruff/issues/new?title=%5BPanic%5D

quoting the executed command, along with the relevant file contents and `pyproject.toml` settings, we'd be very appreciative!

thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', crates\ruff_cli\src\commands\run.rs:112:65

error: `ruff` crashed. This indicates a bug in `ruff`. If you could open an issue at:

https://github.com/astral-sh/ruff/issues/new?title=%5BPanic%5D

quoting the executed command, along with the relevant file contents and `pyproject.toml` settings, we'd be very appreciative!

thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', crates\ruff_cli\src\commands\run.rs:112:65
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by hauntsaninja** [comment] 2023-06-20 22:26
I'm running into this too, cc @Thomasdezeeuw since the panicking line blames to https://github.com/astral-sh/ruff/pull/5120

**Comment by charliermarsh** [comment] 2023-06-20 22:31
I don’t know the cause, but I’ll cut a fix for this tonight.

**Comment by charliermarsh** [comment] 2023-06-20 22:37
I'm taking a look now.

**Comment by charliermarsh** [comment] 2023-06-20 22:42
Are any of these projects public, to help me reproduce?

**Comment by hauntsaninja** [comment] 2023-06-20 22:46
I don't have a public reproducer. If you aren't able to reproduce anywhere, I can try to make one.

**Closed** 2023-06-20 23:01 UTC
Labels: bug
