### ISSUE TITLE
Ruff removes import for fixture used by pytest

### ISSUE THREAD

**Issue by jkugler** [astral-sh/ruff#14539] opened 2024-11-22 20:02 UTC
I searched for "remove pytest fixture"

I have code like this:
```py
from my_code import my_fixture
...
def test_my_thing(my_fixture):
    do_the_test(my_fixture)
```
Ruff sees `my_fixture` as unused and removes the `import` line. This, of course, then breaks the test.

This was done with `ruff check --fix` on ruff 0.8.0, with no special settings.

**Comment by dylwil3** [comment] 2024-11-22 20:30
Sorry to hear this broke your tests, that's frustrating!

This is a bit challenging to address because pytest is (if I understand correctly) performing a custom parse of your test in order to actually "insert" the fixture as an argument to that function. From the point of view of the actual Python specification the imported `my_fixture` really _is_ unused.

Would it be possible in your use-case to:

1. Ignore the rule for test files using `exclude` or a separate config in your tests directory? or
2. Use [conftest.py](https://docs.pytest.org/en/stable/reference/fixtures.html#conftest-py-sharing-fixtures-across-multiple-files) so you don't have to import fixtures?

**Comment by dylwil3** [comment] 2024-11-22 20:38
Ah, and in fact it looks like this is a duplicate of #3295 - so maybe further discussion should be moved there!

**Closed by dylwil3** 2024-11-22 20:38 UTC

**Comment by jkugler** [comment] 2024-11-22 21:23
Thanks!
