### ISSUE TITLE
Q003 autofix for triple nested quotes is not valid python code

### ISSUE THREAD

**Issue by dragon-dxw** [astral-sh/ruff#8739] opened 2023-11-17 11:51 UTC
Version: 0.1.5
input:
`msg = f"Document \"{context['document'].name}\" does not have a PDF."`
error [no args, invoked by precommit]:
`judgments/views/document_full_text.py:38:19: Q003 [*] Change outer quotes to avoid escaping inner quotes`
autofix via `--fix` [via precommit]
`msg = f'Document "{context['document'].name}" does not have a PDF.'`
which is not valid python

ruff config: https://github.com/nationalarchives/ds-caselaw-editor-ui/blob/chore/test-factory-improvements/pyproject.toml

**Comment by sciyoshi** [comment] 2023-11-23 14:06
@dragon-dxw the fixed version is in fact [valid syntax in Python 3.12](https://docs.python.org/3.12/whatsnew/3.12.html#pep-701-syntactic-formalization-of-f-strings). If you set the target Python version to 3.11 or lower in your configuration using `target-version`, this should no longer be marked as an error. See https://github.com/astral-sh/ruff/pull/7588

**Comment by charliermarsh** [comment] 2023-11-24 15:32
Yeah, in my testing this seems to be correctly detected based on the Python version. Do you mind testing if your Python version is set to Python 3.12? Happy to revisit if we're able to reproduce with a lower target-version.

**Closed by charliermarsh** 2023-11-24 15:32 UTC
Labels: bug
