### ISSUE TITLE
option to select the ruff version on the playground

### ISSUE THREAD

**Issue by DetachHead** [astral-sh/ruff#7776] opened 2023-10-03 09:04 UTC
currently the version is displayed here but there's no option to change it (also it's currently outdated since the latest version is 0.0.292)

![image](https://github.com/astral-sh/ruff/assets/57028336/da6d34a1-3e4d-4ad6-b7ec-e3c68e7f9c6a)

it would be nice if there was an option to pick the version, like in the [mypy](https://mypy-play.net) and [typescript](https://www.typescriptlang.org/play) playgrounds

**Comment by zanieb** [comment] 2023-10-03 13:31
We're interested but this is relatively low priority for us. We normally update it automatically on release at https://github.com/astral-sh/ruff/actions/workflows/playground.yaml looks like something is broken.

**Comment by charliermarsh** [comment] 2023-10-03 14:10
Duplicate of https://github.com/astral-sh/ruff/issues/1386.

**Closed by charliermarsh** 2023-10-03 14:10 UTC
