### ISSUE TITLE
(🎁) new rule: useless f-string

### ISSUE THREAD

**Issue by KotlinIsland** [astral-sh/ruff#14780] opened 2024-12-05 00:22 UTC
i see code like this:
```py
a = f"{b}"
```
pointless imo, just use `str(b)` or `format(b)`

**Comment by dhruvmanila** [comment] 2024-12-05 03:59
Duplicate of https://github.com/astral-sh/ruff/issues/10945.

**Closed by dhruvmanila** 2024-12-05 03:59 UTC
Labels: rule, needs-decision
