### ISSUE TITLE
[Feature request] Message on no problems with ruff check

### ISSUE THREAD

**Issue by SimonMarynissen** [astral-sh/ruff#10363] opened 2024-03-12 16:49 UTC
When executing `ruff check` and you get no errors, nothing is output to the terminal. It would be less confusing to the user if a message such as "No problems detected" would appear. It's just a quality of life feature.

**Comment by zanieb** [comment] 2024-03-12 16:57
Hi this is a duplicate of https://github.com/astral-sh/ruff/issues/8553

**Closed by zanieb** 2024-03-12 16:57 UTC
