### ISSUE TITLE
Feature: Replacements for pre-commit rules

### ISSUE THREAD

**Issue by glensc** [astral-sh/ruff#11380] opened 2024-05-12 15:59 UTC
pre-commit is rather slow, so I'm looking for to replace this all:

```yml
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
      - id: fix-byte-order-marker
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-merge-conflict
      - id: check-vcs-permalinks
      - id: destroyed-symlinks
      - id: mixed-line-ending
```

Source: https://github.com/Taxel/PlexTraktSync/blob/ab773cc0b3dc1c3c7efbf8509e5627d1dba1d3dd/.pre-commit-config.yaml#L5-L21

**Comment by glensc** [comment] 2024-05-12 16:03
Replacements found so far:

<table>
<tr>
 <th>pre-commit
 <th>ruff
<tr>
 <td>[trailing-whitespace](https://docs.astral.sh/ruff/rules/trailing-whitespace/)
 <td>
</table>

**Comment by trim21** [comment] 2024-05-13 06:50
Don't think ruff should support this excpet check-builtin-literals...

**Comment by glensc** [comment] 2024-05-15 17:57
Yes, these checks are specific to git commits, i.e do not belong to python linter:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-vcs-permalinks
      - id: destroyed-symlinks

also, these checks are for other language, so useful in git commit hook, but not useful in python linter
      - id: check-yaml
      - id: check-json

not sure of
      - id: fix-byte-order-marker

**Comment by Avasam** [comment] 2024-07-16 23:39
Is this a duplicate of #4073 ?

**Closed** 2024-07-17 06:33 UTC
