### ISSUE TITLE
`unused-import` (`F401`) - error only appears on the last unused import

### ISSUE THREAD

**Issue by DetachHead** [astral-sh/ruff#7972] opened 2023-10-16 03:26 UTC
```py
import foo.bar # no error
import foo.baz # no error
import foo.qux # error
```
https://play.ruff.rs/2f02d4f5-bed4-4cf2-9333-ad28a600c603

**Comment by charliermarsh** [comment] 2023-10-16 03:30
I believe this is a duplicate of https://github.com/astral-sh/ruff/issues/60.

**Closed by charliermarsh** 2023-10-16 03:30 UTC
