### ISSUE TITLE
Feature request: Support for .editorconfig

### ISSUE THREAD

**Issue by Lattay** [astral-sh/ruff#14865] opened 2024-12-09 11:33 UTC
It would be nice if the ruff autoformat system could read settings from .editorconfig, such as indentation related parameters.

**Comment by AlexWaygood** [comment] 2024-12-09 12:51
Thanks for opening the issue -- this is a duplicate of https://github.com/astral-sh/ruff/issues/1530, however :-)

**Closed by AlexWaygood** 2024-12-09 12:51 UTC
Labels: configuration, wish

**Comment by Lattay** [comment] 2024-12-09 13:14
Deeply sorry, I don't know how I missed the other issue.

**Comment by AlexWaygood** [comment] 2024-12-09 13:16
No worries, it happens! GitHub issue search is pretty bad :-)
