### ISSUE TITLE
Is there a way to tell ruff to ignore comments?

### ISSUE THREAD

**Issue by xeon826** [astral-sh/ruff#5899] opened 2023-07-19 20:25 UTC
Since Ruff is made to work in unison with Black, and Black doesn't reformat comments that exceed the line length, is there a way to tell Ruff to ignore these?

**Comment by zanieb** [comment] 2023-07-19 21:18
@xeon826 if you're using Black to enforce your line length I'd just recommend disabling E501 e.g. https://github.com/PrefectHQ/prefect/blob/a3a2f84ba17b8a4469f29fc2a2bfc6dbffd40ed0/.ruff.toml#L1-L2

**Comment by xeon826** [comment] 2023-07-19 21:39
I'm using ruff pre-commit and I added that to its ignore but I'm also using it as a linting tool and it gives me the diagnostic if comments exceed the line length, I feel like `--ignore-comments` would be a useful feature.

**Comment by zanieb** [comment] 2023-07-19 22:54
Why don't you put it in your Ruff configuration so it is always applied?

Note this is also a duplicate of https://github.com/astral-sh/ruff/issues/4429 and https://github.com/astral-sh/ruff/issues/4595

We [cover this in the FAQ](https://beta.ruff.rs/docs/faq/#is-ruff-compatible-with-black) too.

**Comment by xeon826** [comment] 2023-07-19 23:52
I use it to check for line length as a linting tool in my environment, so I'd want it to report on lines that are too long, if I ignored E501 in my pyproject.toml I wouldn't get that behavior, I added an ignore for the rule in pre-commit because I don't want it to report on comments that are too long and prevent the commit. If I told ruff to ignore E501 all together it wouldn't report on it in my IDE diagnostics but that's what I want, by that I mean this:
![image](https://github.com/astral-sh/ruff/assets/5651215/99af9b21-2295-41cf-9b70-f228fe863850)

pyproject.toml
```
[tool.black]
line-length = 88
skip-string-normalization = true
skip-magic-trailing-comma = true
preview = true
target-version = ['py39']

[tool.isort]
profile = 'black'

[tool.ruff]
line-length = 88
target-version = 'py39'
fix = true

```
.pre-commit-config.yaml
```
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.277
    hooks:
      - id: ruff
        files: "\\.(py)$"
        args: [--extend-ignore=E501]
  - repo: https://github.com/pycqa/autoflake
    rev: v2.2.0
    hooks:
      - id: autoflake
        files: "\\.(py)$"
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3.9
        files: "\\.(py)$"
        args: [--config=pyproject.toml]
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        files: "\\.(py)$"
        args: [--settings-path=pyproject.toml]
```

**Comment by tylerlaprade** [comment] 2023-07-23 16:08
>Black doesn't reformat comments that exceed the line length

@xeon826, are you referring to lines containing _only_ a comment? Black has often rearranged my `# type: ignore` and `# noqa` comments, much to my chagrin, especially because I always include descriptive messages about why I'm ignoring something on that line.

**Comment by tylerlaprade** [comment] 2023-07-23 16:12
As an aside, @xeon826, you can 100% replace the functionality of `autoflake` and `isort` with `ruff`, including all the customization in your `pyproject.toml`. This is 99% likely to be true of `flake8` as well, unless you are enabling some esoteric extension rules outside of your `pyproject.toml`

**Comment by xeon826** [comment] 2023-07-24 19:48
@tylerlaprade Lines that are only a comment, yes. I'd remove autoflake but ruff doesn't include the `expand-star-imports` feature

**Comment by zanieb** [comment] 2023-08-15 03:42
Since this is a duplicate and there's a workaround I'm going to close this for bookkeeping purposes. Thanks for raising!

**Closed by zanieb** 2023-08-15 03:42 UTC

**Comment by Qinhaifu** [comment] 2023-11-17 06:54
> I'm using ruff-pre-commit and I added that to its ignore as a workaround but I'm also using ruff as a linting tool and it gives me the diagnostic if comments exceed the line length, I feel like `--ignore-comments` would be a useful feature.

i think so too.

**Comment by tapyu** [comment] 2024-09-24 23:36
> --line-length <LINE_LENGTH>  Set the line-length

Don't we have a solution for this yet?
