### ISSUE TITLE
Formatter incompatibility: extra parentheses around `await` assignment

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/ruff#7420] opened 2023-09-15 20:53 UTC
Given:

```python
result = await self.request(
    f"/applications/{int(application_id)}/guilds/{int(scope)}/commands/{int(command_id)}/permissions"
)
```

Ruff formats as:

```python
result = (
    await self.request(
        f"/applications/{int(application_id)}/guilds/{int(scope)}/commands/{int(command_id)}/permissions"
    )
)
```

While Black formats as:

```python
result = await self.request(
    f"/applications/{int(application_id)}/guilds/{int(scope)}/commands/{int(command_id)}/permissions"
)
```

Sourced from: https://github.com/astral-sh/ruff/issues/7394.

**Comment by MichaReiser** [comment] 2023-09-15 21:01
That could simply be because the awaited expression exceeds the line width. We would need to use best fitting if we want to avoid this for unbreakable expressions

**Comment by MichaReiser** [comment] 2023-09-16 14:37
Closing as duplicate of #7431 (They have the same root cause)

**Closed** 2023-09-16 17:10 UTC
Labels: formatter, accepted
