### ISSUE TITLE
In Jupyter Notebook ruff should ignore bash cells

### ISSUE THREAD

**Issue by shaneahmed** [astral-sh/ruff#6445] opened 2023-08-09 12:01 UTC
The command you invoked: `ruff check . --fix` 

Pre-commit yaml available here: https://github.com/TissueImageAnalytics/tiatoolbox/blob/d722f67f4c7584db6a6607544477613dee95aac0/.pre-commit-config.yaml#L75

The current Ruff settings (any relevant sections from your `pyproject.toml`) : https://github.com/TissueImageAnalytics/tiatoolbox/blob/d722f67f4c7584db6a6607544477613dee95aac0/pyproject.toml#L74

The current Ruff version (`ruff --version`) : 0.0.283

Pull request for this bug is available at this link: https://github.com/TissueImageAnalytics/tiatoolbox/pull/689

Issue:
The new version 0.0.283 generates errors for jupyter notebooks such as: `E402 Module level import not at top of file` when the first cell is a bash script which installs the package. This is useful for new users who want to test the jupyter notebooks on online platforms such as Google Colab or Anaconda Cloud.

While testing Jupyter Notebooks, ruff should ignore bash scripts at the top of the cell e.g., in this file https://github.com/TissueImageAnalytics/tiatoolbox/blob/upgrade-ruff-version/examples/01-wsi-reading.ipynb the first cell installs the package on Colab which is not available already. Similarly print statements in this cell should be ignored.

**Comment by dhruvmanila** [comment] 2023-08-09 13:55
(closing as intended behavior)

**Closed by dhruvmanila** 2023-08-09 13:55 UTC

**Comment by shaneahmed** [comment] 2023-08-09 16:04
I understand Jupyter notebooks is still experimental but it is very useful. Thanks for this :)

Thanks for the suggestions. I now understand the problem and have modified the notebooks accordingly.
