### ISSUE TITLE
Nested quotation marks in f-string, ignores parse error

### ISSUE THREAD

**Issue by andy-lz** [astral-sh/ruff#11221] opened 2024-04-30 21:59 UTC
In Python 3.9.18, the below code will succeed silently with ruff format and ruff check, even though it has a SyntaxError:

```
# file.py
my_str = f"1+1={"2"}"


>> ruff format file.py #succeeds
>> python file.py  # fails with SyntaxError
```

**Comment by AlexWaygood** [comment] 2024-04-30 22:06
Thanks for opening the issue! I'm going to close this as a duplicate of #6591 (the syntax in question here is legal on Python 3.12+, but not on lower versions)

**Closed by AlexWaygood** 2024-04-30 22:06 UTC
Labels: parser
