### ISSUE TITLE
[Panic] broken pipe leads to panic

### ISSUE THREAD

**Issue by mitsuhiko** [astral-sh/ruff#13483] opened 2024-09-23 13:21 UTC
```
ruff analyze graph --preview| bat -l json --color=always
```

Hit quit, be presented with a broken pipe:

```
error: Ruff crashed. If you could open an issue at:

    https://github.com/astral-sh/ruff/issues/new?title=%5BPanic%5D

...quoting the executed command, along with the relevant file contents and `pyproject.toml` settings, we'd be very appreciative!

thread 'main' panicked at library/std/src/io/stdio.rs:1118:9:
failed printing to stdout: Broken pipe (os error 32)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Classic rust command line tool behavior :)

**Comment by charliermarsh** [comment] 2024-09-23 13:22
Lol. A duplicate of #13442.

**Closed** 2024-09-23 13:48 UTC
Labels: bug
