### ISSUE TITLE
Pandas boolean if statement correction bug 

### ISSUE THREAD

**Issue by Stas1beat** [astral-sh/ruff#8023] opened 2023-10-17 19:58 UTC
Currently Ruff changes the boolean if statement from the format `if <field> == True:` (or False). to the format `if <field> is True:`
This format doesn't work in Pandas, `if <field> is True:` always returns a False result.
Thank you!

**Comment by zanieb** [comment] 2023-10-17 20:30
Hi thanks for the report. I believe this is a duplicate of https://github.com/astral-sh/ruff/issues/4560 — let me know if your problem is not captured there!

**Closed by zanieb** 2023-10-17 20:30 UTC
