### ISSUE TITLE
E0601/F821: Using variable 'x' before assignment (used-before-assignment) not working

### ISSUE THREAD

**Issue by FrancoisMasson1990** [astral-sh/ruff#14821] opened 2024-12-06 15:56 UTC
ruff does not seem to be able to detect unbound variables in python.

Example:

```python
def test() -> int:
    try:
        continue
        x = 1
    except Exception:
        pass
    finally:
        return x
````

Return no error of unbound variables

**Comment by MichaReiser** [comment] 2024-12-06 16:26
I think this is the same as https://github.com/astral-sh/ruff/issues/2493 and https://github.com/astral-sh/ruff/issues/6902 so I'll close this in favor of an existing issue. 

The problem is that Ruff's analysis isn't branch-sensitive. It doesn't know that you can reach the `finally` with `x` unbound if the `except` branch is taken at runtime (and only if the except branch is taken before `x` gets declared). 

We work on an improved analysis engine that can catch this kind of error.

**Closed by MichaReiser** 2024-12-06 16:26 UTC
