### ISSUE TITLE
Ruff is removing used imports

### ISSUE THREAD

**Issue by lcsvcn** [astral-sh/ruff#11518] opened 2024-05-23 17:46 UTC
Removing used imports (probably wrong classified as "unused"

```
ruff check . --fix --verbose
ruff format --verbose
```
Here is autoformat configured with commands above:
<img width="1274" alt="Screenshot 2024-05-23 at 14 36 51" src="https://github.com/astral-sh/ruff/assets/6011385/92f917b5-08e1-4c3b-a228-f61df9ed3689">

here is a function that is using the import:
<img width="424" alt="Screenshot 2024-05-23 at 14 37 29" src="https://github.com/astral-sh/ruff/assets/6011385/e7d1ca0a-1a17-4570-bbe8-e93c4ca0ee56">

The ruff format insists in remove used import, it was not first time, but now it is first time it was doing several times in a row.

**Comment by charliermarsh** [comment] 2024-05-23 17:59
Can you please include a full reproducible example, like a Python file that demonstrates the bug? That snippet alone isn’t enough (and can’t be copy-pasted) since it doesn’t contain any imports.

**Comment by zanieb** [comment] 2024-05-23 18:04
Might be a duplicate of https://github.com/astral-sh/ruff/issues/8691

**Comment by charliermarsh** [comment] 2024-05-26 17:17
Closing as a dupe, looks that way.

**Comment by charliermarsh** [comment] 2024-05-28 01:53
I think it's actually slightly different than #8691.

**Closed** 2024-05-28 18:47 UTC
Labels: bug
