### ISSUE TITLE
[red-knot] Port more tests in `infer.rs` to mdtest

### ISSUE THREAD

**Issue by AlexWaygood** [astral-sh/ruff#14166] opened 2024-11-07 16:01 UTC
Following https://github.com/astral-sh/ruff/pull/14126, mdtest now supports Python snippets that contain invalid syntax. This enables us to port more tests in `infer.rs` over to the mdtest framework; we should do so

**Comment by carljm** [comment] 2024-11-07 21:39
Closing as duplicate of https://github.com/astral-sh/ruff/issues/13696

**Closed by carljm** 2024-11-07 21:39 UTC
Labels: help wanted, testing, red-knot

**Comment by AlexWaygood** [comment] 2024-11-07 21:43
Oh oops, I thought that had been closed... sorry!
