### ISSUE TITLE
support module-level banned imports in `flake8-tidy-imports.banned-api`

### ISSUE THREAD

**Issue by DetachHead** [astral-sh/ruff#7974] opened 2023-10-16 04:33 UTC
i wrote a pylint plugin to enforce certain rules about which modules can import each other within my project: https://github.com/detachhead/pylint-module-boundaries

but it would be nice to be able to ditch pylint in favor of ruff. if `flake8-tidy-imports.banned-api` supported setting rules per module that would render the pylint plugin obsolete. something like this:

```toml
[tool.ruff.flake8-tidy-imports.banned-api]
"foo.bar".msg = "this import is banned globally"

[tool.ruff.flake8-tidy-imports.banned-api.per-file-rules."bar/**/*.py"]
"foo.bar".msg =  "this import is banned in the `bar` module"
```

**Comment by charliermarsh** [comment] 2023-10-16 13:34
I believe this is a dupe of https://github.com/astral-sh/ruff/issues/7696.

**Closed by charliermarsh** 2023-10-16 13:34 UTC
