### ISSUE TITLE
# type:ignore is not well placed

### ISSUE THREAD

**Issue by sylvainmouquet** [astral-sh/ruff#10440] opened 2024-03-17 23:53 UTC
Hello,

I have this code :
```
result = await query.find_all(self.connection, foo=bar, bar=foo, foofoo=barbar)  # type: ignore
```

ruff generate this result : 
```
result = await query.find_all(
                self.connection, foo=bar, bar=foo, foofoo=barbar
            )   # type: ignore
```
it's possible configure the position of # type : ignore is present (first line and not last line) or let's it where there is a 'syntax' error ?

**Comment by MichaReiser** [comment] 2024-03-18 07:41
Hy @sylvainmouquet 

Are you using `ruff check` or `ruff format`?

**Comment by sylvainmouquet** [comment] 2024-03-18 09:28
well i close the issue, i don't reproduce and i am not sure if it's with ruff or others tools. i will open a new issue when i track the error

**Comment by aberres** [comment] 2024-03-18 09:29
I also had some of these when switching to `ruff format`.

`result = await query.find_all(self.connectionnnnnnnnnnnnn, foo=bar, bar=foo, foofoo=barbar)  # type: ignore`

`$ ruff format`

==>

```python
result = await query.find_all(
    self.connectionnnnnnnnnnnnn, foo=bar, bar=foo, foofoo=barbar
)  # type: ignore
```

**Comment by aberres** [comment] 2024-03-18 09:30
@sylvainmouquet Try with a longer line.

**Comment by sylvainmouquet** [comment] 2024-03-18 09:36
ok i try again

**Comment by sylvainmouquet** [comment] 2024-03-18 09:44
@aberres ok i reproduce

**Comment by MichaReiser** [comment] 2024-03-18 14:59
>  it's possible configure the position of # type : ignore is present (first line and not last line) or let's it where there is a 'syntax' error ?

I suspect a configuration option would need to be per file or line because you probably want a different placement depending on the code snipped. 

Unfortunately, determining which node triggers the type error (it could also be multiple ones) isn't feasible in the formatter because it would come at a huge performance penalty. The formatter would need to ask a type-checker which node the comment is suppressing, and that can easily take seconds if you, e.g., use mypy.

What you can do is to move the type ignore comment manually, depending on which node triggers the typing error

```python
result = await query.find_all( # type: ignore
    self.connection, foo=bar, bar=foo, foofoo=barbar
)   
```

```python
result = await query.find_all(
    self.connection,
    foo=bar,
    bar=foo,
    foofoo=barbar,  # type: ignore
)
```

Putting it at the end of line doesn't work today (see https://github.com/astral-sh/ruff/issues/7368)

```python
result = await query.find_all(
    self.connection, foo=bar, bar=foo, foofoo=barbar # type: ignore
)   
```

I know moving type comments is frustrating, especially if you're migrating a project. I tried to explain some of ruff's reasoning in [this discussion](https://github.com/astral-sh/ruff/discussions/6670) and am interested to find better heuristics for pragma comment placement.

**Comment by aberres** [comment] 2024-03-18 16:11
I agree that it is not too much of a problem in practice. When switching from Black to Ruff, I moved some ignores/noqas and carried on.

One thing I wonder: In the case above, the comment stays at the end. Is there any case in which this will be the correct line for any tool? Or might moving it right behind the opening `(` be the safer bet?

**Comment by MichaReiser** [comment] 2024-03-18 16:35
> One thing I wonder: In the case above, the comment stays at the end. Is there any case in which this will be the correct line for any tool? Or might moving it right behind the opening ( be the safer bet?

Keeping it at the end could be the right call for `noqa` comments and maybe even `type: ignore`. For example if there's an error in the expression: `foo=some_expr_with_a_typing_or_lint_error`

**Comment by aberres** [comment] 2024-03-18 16:51
Oh right, got some `) # type: ignore[call-arg]` in my code. I thought `mypy` would expect them in the first line.

**Comment by sylvainmouquet** [comment] 2024-03-19 06:50
In this case, I prefer not to format the line when there is `# type: ignore`. And have an option for the user to define the formatting when it depends on the context.
In my opinion, automatic formatting must be idempotent, safe and can be executed as part of an automated process. In addition, when the result requires manual verification, this can be carried out using an option. As in the case of a pull request, the user accepts or corrects the proposal.

**Comment by MichaReiser** [comment] 2024-03-19 08:42
> In this case, I prefer not to format the line when there is # type: ignore.

The problem isn't specific to `type: ignore`. It applies to all pragma comments. That would mean that the formatter should not format any trailing comment that possibly could be a pragma comment, which could be any comment.

> In my opinion, automatic formatting must be idempotent, safe and can be executed as part of an automated process

I agree that that's the ideal and we try hard to place comments so that if it happens to be unsafe, that we reduce the scope of suppression comments so that the tool using the pragma comment can make you aware of a misplaced comment.

> And have an option for the user to define the formatting when it depends on the context.

Could you explain what you mean by "define the formatting" and how that would look/work?

**Comment by sylvainmouquet** [comment] 2024-03-19 11:46
Comments pragma refers to not python grammar.

I am sharing my ideas. 
To format the code, there is 2 steps: create the AST + apply the formatting. 
The formatting is like CSS, it doesn't interact to the structure of the document, it's only styling
The AST is to create a tree of blocks to follow the grammar of the langage. It's a kind of reverse engineering. (It could be done by IA)

When there is  pragma, things get more complicated, because this is a human decision, outside the python language.
The user has made a choice that cannot be calculated in advance.

It comes down to a decision tree: you can make the decision for the user, or you can leave the choice to him.

The decision he has made can become a new rule.

So we'd have:
- python rules
- custom user rules

**Closed** 2024-03-19 11:55 UTC
Labels: suppression, style
