### ISSUE TITLE
New rule: find unused placeholders for f-strings

### ISSUE THREAD

**Issue by Sanchoyzer** [astral-sh/ruff#9638] opened 2024-01-24 19:55 UTC
`ruff==0.1.14`
```
def func(my_var: int) -> int:
    var = my_var * 2
    print('var is {var}')
    return var
```
It might be useful if Ruff will find such places, I made a typo: `'var is {var}'` instead of `f'var is {var}'`

**Comment by trag1c** [comment] 2024-01-24 20:23
I think this is a duplicate of #8151

**Comment by charliermarsh** [comment] 2024-01-24 20:25
Agreed -- I'd like to add this!

**Closed by charliermarsh** 2024-01-24 20:25 UTC
