### ISSUE TITLE
Proposal: detach file output format from output format

### ISSUE THREAD

**Issue by penguinolog** [astral-sh/ruff#8251] opened 2023-10-26 12:59 UTC
Use-case:
`ruff` is used on jenkins CI. Text output is usually read by user, but also collected and parsed JUnitXML log.
At current moment is no method to specify file output format different from stdout otput format.
Proposal:
add `--output-file-format` CLI option in addition to existing `--output-file` option

**Comment by zanieb** [comment] 2023-10-26 13:46
Hi This is a duplicate of https://github.com/astral-sh/ruff/issues/2388

I like the `--output-file-format` option.

**Closed by zanieb** 2023-10-26 13:46 UTC
