### ISSUE TITLE
PLW3201: Add setting to add custom names allowed for dunders

### ISSUE THREAD

**Issue by ThiefMaster** [astral-sh/ruff#8808] opened 2023-11-21 15:31 UTC
For example, [SQLAlchemy uses](https://docs.sqlalchemy.org/en/20/orm/mapping_api.html#sqlalchemy.orm.DeclarativeBase.__table__) various names such as  `__tablename__` and `__table_args__`. Adding a noqa in tons of models would be extremely noisy.

**Comment by zanieb** [comment] 2023-11-21 16:09
This looks like a duplicate of https://github.com/astral-sh/ruff/issues/8732

**Closed by zanieb** 2023-11-21 16:09 UTC
