### ISSUE TITLE
Formatter undocumented deviation: wrapping with annotation only and comment

### ISSUE THREAD

**Issue by JonathanPlasse** [astral-sh/ruff#7322] opened 2023-09-12 21:15 UTC
Black formatting
```python
class Animatable(Protocol):
    """Protocol for objects that can be animated."""

    animation_data: bpy.types.AnimData  # TODO(jonathan): Change to Optional when fake-bpy-module is updated
```
Ruff formatting
```python
class Animatable(Protocol):
    """Protocol for objects that can be animated."""

    animation_data: (
        bpy.types.AnimData
    )  # TODO(jonathan): Change to Optional when fake-bpy-module is updated
```
Ruff 0.0.289 with line-length 100

I prefer Black formatting

**Comment by MichaReiser** [comment] 2023-09-13 06:09
I can see how Black's formatting may seem better but Black's code exceeds the configured line width of 100, whereas Ruff's formatting stays in the limit. 

Black is also a bit inconsistent here because it uses the same formatting as ruff if you change this to an assignment:

```python
animation_data = (
    bpy.types.AnimData
)  # TODO(jonathan): Change to Optional when fake-bpy-module is updated
```

I propose that we stick to Ruff's layout because:
* It is more consistent with other syntax
* It stays within the configured line length

**Comment by MichaReiser** [comment] 2023-09-13 07:08
Closing as duplicate of ##7322

**Closed by MichaReiser** 2023-09-13 07:08 UTC
Labels: wontfix, formatter
