### ISSUE TITLE
Suggestion: per-file-includes

### ISSUE THREAD

**Issue by kobymeir** [astral-sh/ruff#5118] opened 2023-06-15 10:43 UTC
As shown in the configuration there is an option to exclude rules:
https://beta.ruff.rs/docs/configuration/#using-pyprojecttoml

I want an option to include rules on specific files patterns
for example, I want to force specific rules on `_test.py` files in my project.

```
# enforce `E402` (import violations) in all `*_test.py` files.
[tool.ruff.per-file-ignores]
"*_test.py" = ["E402"]
```

**Comment by charliermarsh** [comment] 2023-06-15 13:41
👍 I do want to support something like this, though I believe this is a duplicate of #3172.

**Closed by charliermarsh** 2023-06-15 13:41 UTC

**Comment by kobymeir** [comment] 2023-06-15 14:45
My use case is a bit different, as I'm trying to use the banned-api https://beta.ruff.rs/docs/settings/#flake8-tidy-imports-banned-api within `*_test.py` files.

Maybe this example of what i'm try to accomplish is better:
```ini
[tool.ruff.flake8-tidy-imports]
[tool.ruff.flake8-tidy-imports.banned-api]
"random".msg = "The random module is forbidden within test files, as it might cause them not to be deterministic"
"random".pattern = "**/*_test.py"
```
